### ISSUE TITLE
Write a scrapper to download dataset from StackOverflow

### ISSUE THREAD

**Issue by gksoriginals** [Navan0/DeepLI#2]
Potential dataset for training the DeepLI model isa collection of questions in StackOverflow regarding bash commands and the corresponding commands.

* Input - Question in StackOverflow about the command. 
* Output - Corresponding bash command.

Need to write a scrapper that scrap such Questions and resulting commands.

**Comment by navan0** [comment]
Added a dataset directory and dataset generating script, check and review PR
